# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: move.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='move.proto',
  package='',
  serialized_pb=_b('\n\nmove.proto\"7\n\x08Movement\x12\x0c\n\x04slug\x18\x01 \x01(\x05\x12\x1d\n\tdirection\x18\x02 \x01(\x0e\x32\n.Direction*2\n\tDirection\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x06\n\x02UP\x10\x03\x12\x08\n\x04\x44OWN\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UP', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=71,
  serialized_end=121,
)
_sym_db.RegisterEnumDescriptor(_DIRECTION)

Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
LEFT = 1
RIGHT = 2
UP = 3
DOWN = 4



_MOVEMENT = _descriptor.Descriptor(
  name='Movement',
  full_name='Movement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='slug', full_name='Movement.slug', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='Movement.direction', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=69,
)

_MOVEMENT.fields_by_name['direction'].enum_type = _DIRECTION
DESCRIPTOR.message_types_by_name['Movement'] = _MOVEMENT
DESCRIPTOR.enum_types_by_name['Direction'] = _DIRECTION

Movement = _reflection.GeneratedProtocolMessageType('Movement', (_message.Message,), dict(
  DESCRIPTOR = _MOVEMENT,
  __module__ = 'move_pb2'
  # @@protoc_insertion_point(class_scope:Movement)
  ))
_sym_db.RegisterMessage(Movement)


# @@protoc_insertion_point(module_scope)
