# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: move.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Mapping.Interface.map_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='move.proto',
  package='',
  serialized_pb=_b('\n\nmove.proto\x1a\x1bMapping/Interface/map.proto\"I\n\x0fMovementRequest\x12\x0c\n\x04p_id\x18\x01 \x01(\x05\x12\x1a\n\x0b\x64\x65stination\x18\x02 \x01(\x0b\x32\x05.Cell\x12\x0c\n\x04type\x18\x03 \x01(\t\"K\n\x0fUpdatedPosition\x12\x0c\n\x04p_id\x18\x01 \x01(\x05\x12\r\n\x05x_pos\x18\x02 \x01(\x05\x12\r\n\x05y_pos\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\t')
  ,
  dependencies=[Mapping.Interface.map_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOVEMENTREQUEST = _descriptor.Descriptor(
  name='MovementRequest',
  full_name='MovementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p_id', full_name='MovementRequest.p_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destination', full_name='MovementRequest.destination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='MovementRequest.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=116,
)


_UPDATEDPOSITION = _descriptor.Descriptor(
  name='UpdatedPosition',
  full_name='UpdatedPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p_id', full_name='UpdatedPosition.p_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_pos', full_name='UpdatedPosition.x_pos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_pos', full_name='UpdatedPosition.y_pos', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='UpdatedPosition.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=193,
)

_MOVEMENTREQUEST.fields_by_name['destination'].message_type = Mapping.Interface.map_pb2._CELL
DESCRIPTOR.message_types_by_name['MovementRequest'] = _MOVEMENTREQUEST
DESCRIPTOR.message_types_by_name['UpdatedPosition'] = _UPDATEDPOSITION

MovementRequest = _reflection.GeneratedProtocolMessageType('MovementRequest', (_message.Message,), dict(
  DESCRIPTOR = _MOVEMENTREQUEST,
  __module__ = 'move_pb2'
  # @@protoc_insertion_point(class_scope:MovementRequest)
  ))
_sym_db.RegisterMessage(MovementRequest)

UpdatedPosition = _reflection.GeneratedProtocolMessageType('UpdatedPosition', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEDPOSITION,
  __module__ = 'move_pb2'
  # @@protoc_insertion_point(class_scope:UpdatedPosition)
  ))
_sym_db.RegisterMessage(UpdatedPosition)


# @@protoc_insertion_point(module_scope)
