# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commodities.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commodities.proto',
  package='',
  serialized_pb=_b('\n\x11\x63ommodities.proto\"I\n\tCommodity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nelasticity\x18\x02 \x01(\x02\x12\x0e\n\x06rarity\x18\x03 \x01(\x02\x12\n\n\x02id\x18\x04 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMODITY = _descriptor.Descriptor(
  name='Commodity',
  full_name='Commodity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Commodity.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elasticity', full_name='Commodity.elasticity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rarity', full_name='Commodity.rarity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='Commodity.id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['Commodity'] = _COMMODITY

Commodity = _reflection.GeneratedProtocolMessageType('Commodity', (_message.Message,), dict(
  DESCRIPTOR = _COMMODITY,
  __module__ = 'commodities_pb2'
  # @@protoc_insertion_point(class_scope:Commodity)
  ))
_sym_db.RegisterMessage(Commodity)


# @@protoc_insertion_point(module_scope)
