# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: region.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import map_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='region.proto',
  package='',
  serialized_pb=_b('\n\x0cregion.proto\x1a\tmap.proto\"J\n\x0bTerrainDist\x12\r\n\x05river\x18\x01 \x01(\x02\x12\x0b\n\x03sea\x18\x02 \x01(\x02\x12\x10\n\x08mountain\x18\x03 \x01(\x02\x12\r\n\x05plain\x18\x04 \x01(\x02\"I\n\x06Region\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x05\x63\x65lls\x18\x02 \x03(\x0b\x32\x05.Cell\x12\x1d\n\x07terrain\x18\x03 \x01(\x0b\x32\x0c.TerrainDist\"\"\n\x07Message\x12\x17\n\x06region\x18\x01 \x01(\x0b\x32\x07.Region')
  ,
  dependencies=[map_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TERRAINDIST = _descriptor.Descriptor(
  name='TerrainDist',
  full_name='TerrainDist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='river', full_name='TerrainDist.river', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sea', full_name='TerrainDist.sea', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mountain', full_name='TerrainDist.mountain', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='plain', full_name='TerrainDist.plain', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=101,
)


_REGION = _descriptor.Descriptor(
  name='Region',
  full_name='Region',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Region.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cells', full_name='Region.cells', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='terrain', full_name='Region.terrain', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=176,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='Message.region', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=212,
)

_REGION.fields_by_name['cells'].message_type = map_pb2._CELL
_REGION.fields_by_name['terrain'].message_type = _TERRAINDIST
_MESSAGE.fields_by_name['region'].message_type = _REGION
DESCRIPTOR.message_types_by_name['TerrainDist'] = _TERRAINDIST
DESCRIPTOR.message_types_by_name['Region'] = _REGION
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

TerrainDist = _reflection.GeneratedProtocolMessageType('TerrainDist', (_message.Message,), dict(
  DESCRIPTOR = _TERRAINDIST,
  __module__ = 'region_pb2'
  # @@protoc_insertion_point(class_scope:TerrainDist)
  ))
_sym_db.RegisterMessage(TerrainDist)

Region = _reflection.GeneratedProtocolMessageType('Region', (_message.Message,), dict(
  DESCRIPTOR = _REGION,
  __module__ = 'region_pb2'
  # @@protoc_insertion_point(class_scope:Region)
  ))
_sym_db.RegisterMessage(Region)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'region_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
